# Use an official Python runtime as a parent image
FROM ubuntu:18.04

MAINTAINER Harshal Deshpande "hardesh1deshpande@gmail.com"

# To avoid tzdata asking for geographic location...
ENV DEBIAN_FRONTEND noninteractive

# Set the working directory to /root
ENV DIRPATH /root/
WORKDIR $DIRPATH

#Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get update && apt-get install -y git cmake build-essential pkg-config

# Install xvfb to provide a display to container for GUI realted testing.
RUN apt-get update && apt-get install -y xvfb

# Installing ROS on Ubuntu 18.04
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

RUN apt-get update && apt-get install ros-melodic-desktop-full
RUN source /opt/ros/melodic/setup.bash

RUN apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
RUN rosdep init && rosdep update

RUN apt install python-wstool python-catkin-tools  \
	ros-melodic-joint-state-controller  \
	ros-melodic-effort-controllers  \
	ros-melodic-joint-trajectory-controller  \
	ros-melodic-position-controllers

RUN mkdir -p catkin_ws/src && cd catkin_ws/src
RUN git clone https://github.com/ERC-BPGC/omnibase.git
RUN wstool init && wstool merge omnibase/omnibase_https.rosinstall && wstool update
RUN cd .. && catkin build
