omnibase:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    front_right_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_front_right_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}

    front_left_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_front_left_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}

    back_right_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_back_right_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}

    back_left_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_back_left_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}